# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aeafcb1b8d9b4d63ffce6669eb19e5829ad8195ad636ae30ab14ce0f7f39d1aec3ef42fea15c46f76517712084caff969a4e0711c7e74fec06fc34fc01fe98a

test:
  secret_key_base: cca8ebba7cf4cdce60bac751ad9bcfb00255966b855c0db80f05058f5c76749a083acb7c4218a4c41b4ddee1b287f009d314f9da4b678294a2d353b98dfc590f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
